name: makefile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  makefile:
    name: Run Makefile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Execute make
      shell: bash
      run: make
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: nuget/*

    - name: Push to nuget.org
      if: github.ref == 'refs/heads/main'
      shell: bash
      run: dotnet nuget push "nuget/*.nupkg" -k "$KEY" -s https://api.nuget.org/v3/index.json
      env:
        KEY: ${{ secrets.NUGET_API_KEY }}
